[package]
name = "ratelimit"
version = "0.3.1"
authors = ["Brian Martin <brayniac@gmail.com>"]

license = "MIT OR Apache-2.0"

description = "a token bucket ratelimiter"

homepage = "https://github.com/brayniac/ratelimit"
documentation = "http://brayniac.github.io/ratelimit"
repository = "https://github.com/brayniac/ratelimit"

readme = "README.md"

keywords = [ "ratelimit", "tokenbucket", "rate", "token", "bucket" ]

include = [ "src/**/*", "README.md", "LICENSE-*", "Cargo.toml" ]

[dependencies]
shuteye = "0.2.0"

[features]
unstable = []
